Multirepo + images signing (#59)
* * add sign images code from `feat/signing_images` branch

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * bump WERF_SIGN_VERSION

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * try download werf from fox with CI_JOB_TOKEN

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * try download werf from fox with CI_JOB_TOKEN

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * try download werf from fox with WERF_SIGN_PACKAGE_TOKEN

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * fix werf install

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * debug

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * remove debug statements

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * disable ELF files signing

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * require WERF_VAULT_AUTH_ROLE_ID or WERF_VAULT_AUTH_JWT

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * require WERF_VAULT_AUTH_ROLE_ID or WERF_VAULT_AUTH_JWT

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * add some emojis

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

* * do not enable images signing (comment WERF_SIGN_VERSION var) by default

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

---------

Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

diff --git a/templates/multi-repo/Setup.gitlab-ci.yml b/templates/multi-repo/Setup.gitlab-ci.yml
--- a/templates/multi-repo/Setup.gitlab-ci.yml
+++ b/templates/multi-repo/Setup.gitlab-ci.yml
@@ -14,6 +14,26 @@
 #   SVACE_ANALYZE_SSH_USER: - ssh user to connect with to svace analyze vm
 #   SVACE_ANALYZE_SSH_PRIVATE_KEY_B64 - svace analyze server ssh private key
 
+#   Variables for sign (must be configured in GitLab CI/CD Variables):
+#   WERF_ELF_PGP_PRIVATE_KEY_FINGERPRINT - GPG key fingerprint
+#   WERF_ELF_PGP_PRIVATE_KEY_PASSPHRASE - GPG key passphrase
+#   VAULT_ADDR - URL to Vault address
+#   WERF_SIGN_CERT - certificate for signing images
+#   WERF_SIGN_INTERMEDIATES - intermediate certificates
+#   VAULT_ROLE_ID - ID role for access to Vault
+#   VAULT_SECRET_ID - secret ID for access to Vault
+#   WERF_SIGN_KEY - private key for signing
+#
+#   Variables configured in ci file:
+#   WERF_BSIGN_ELF_FILES=1 - enable binary signing
+#   WERF_SIGN_MANIFEST: "true" - enable image signing
+#   WERF_ANNOTATE_LAYERS_WITH_DM_VERITY_ROOT_HASH = true - add dm-verity hashes to layers
+#   WERF_SIGN_ELF_FILES: "1" - enable elf signing
+#
+#   PACKAGE_TOKEN - token for access to internal repository for downloading werf binary
+#
+#   The GPG key is located locally on the Gitlab runner
+#   Werf must be installed manually
 
 variables:
   ##############################
@@ -55,6 +75,13 @@ variables:
     value: ${CI_REGISTRY_IMAGE}/${MODULES_MODULE_NAME}
   WERF_VERSION: "2 stable"
 
+  # See:https://wiki.flant.ru/doc/podpisanie-obrazov-vneshnih-modulej-2JzTJwTPEe
+  # WERF_SIGN_VERSION: "v2.51.0+dk"
+  WERF_SIGN_MANIFEST: "1"
+  WERF_SIGN_ELF_FILES: "0"
+  WERF_BSIGN_ELF_FILES: "0"
+  WERF_ANNOTATE_LAYERS_WITH_DM_VERITY_ROOT_HASH: "1"
+
 stages:
   - lint
   - cleanup
@@ -85,16 +112,47 @@ stages:
   before_script:
     # Setup trdl
     - |
-      trdl_version=$(curl -s https://tuf.trdl.dev/targets/channels/0/stable)
-      curl -sSLO "https://tuf.trdl.dev/targets/releases/$trdl_version/linux-amd64/bin/trdl"
-      install -D trdl ~/bin/trdl
-      rm trdl
-      export PATH=$PATH:~/bin
+      TRDL_ROOT="${HOME}/.trdl"
+      trdl_target_version=$(curl -s https://tuf.trdl.dev/targets/channels/0/stable)
+      TRDL_BIN="${TRDL_ROOT}/releases/${trdl_target_version}/trdl"
+      if [[ ! -x "${TRDL_BIN}" ]]; then
+        echo "🔧 Installing trdl ${trdl_target_version}..."
+        mkdir -p "${TRDL_ROOT}/releases/${trdl_target_version}"
+        curl -sSLO "https://tuf.trdl.dev/targets/releases/${trdl_target_version}/linux-amd64/bin/trdl"
+        mv trdl "${TRDL_BIN}"
+        chmod +x "${TRDL_BIN}"
+      fi
+      ln -sfn "releases/${trdl_target_version}" "${TRDL_ROOT}/current"
+      export PATH="${TRDL_ROOT}/current:${PATH}"
 
     # Setup werf
     - |
-      trdl add werf https://tuf.werf.io 1 b7ff6bcbe598e072a86d595a3621924c8612c7e6dc6a82e919abe89707d7e3f468e616b5635630680dd1e98fc362ae5051728406700e6274c5ed1ad92bea52a2
-      source $(trdl use werf ${WERF_VERSION:-1.2 stable})
+      if [[ -n "${WERF_SIGN_VERSION}" ]]; then
+        if [[ -z "${WERF_SIGN_PACKAGE_TOKEN}" ]]; then
+          echo "❌ ERROR: WERF_SIGN_PACKAGE_TOKEN is not set!"
+          echo "Please get token from delivery team and configure this variable in GitLab CI/CD settings -> Variables"
+          exit 1
+        fi
+
+        echo "🔧 Downloading werf $WERF_SIGN_VERSION binary with signing support from internal repository..."
+
+        mkdir -p ${HOME}/bin
+
+        curl --fail -sSL -o ${HOME}/bin/werf \
+        -H "PRIVATE-TOKEN: $WERF_SIGN_PACKAGE_TOKEN" \
+        "${CI_API_V4_URL}/projects/4052/packages/generic/werf/${WERF_SIGN_VERSION}/werf"
+        chmod +x ${HOME}/bin/werf
+        export PATH=${HOME}/bin:$PATH
+      else
+        echo "🔧 Installing werf $WERF_VERSION via trdl..."
+        trdl add werf https://tuf.werf.io 1 b7ff6bcbe598e072a86d595a3621924c8612c7e6dc6a82e919abe89707d7e3f468e616b5635630680dd1e98fc362ae5051728406700e6274c5ed1ad92bea52a2
+        source $(trdl use werf ${WERF_VERSION:-1.2 stable})
+      fi
+
+      # Check werf version
+      type -a werf
+      werf version
+
       source $(werf ci-env gitlab --as-file)
 
       # Login to gitlab registry by default
@@ -107,25 +165,69 @@ stages:
       if [[ "x${MODULES_REGISTRY_PASSWORD}" == "x" ]]; then
         MODULES_REGISTRY_PASSWORD="${CI_REGISTRY_PASSWORD}"
       fi
-      echo "Logging in to registry ${MODULES_REGISTRY}..."
+      echo "🔑 Logging in to registry ${MODULES_REGISTRY}..."
       werf cr login -u ${MODULES_REGISTRY_LOGIN} -p ${MODULES_REGISTRY_PASSWORD} ${MODULES_REGISTRY}
+
+    - |
+      if [[ -n "${WERF_SIGN_VERSION}" ]]; then
+        echo "🔐 Checking required signing variables..."
+
+        # Variables that must be set in secrets CI/CD
+        REQUIRED_SIGNING_VARS=(
+          "VAULT_ADDR"
+        )
+
+        if [[ "${WERF_SIGN_MANIFEST}" == "1" ]]; then
+          REQUIRED_SIGNING_VARS+=("WERF_SIGN_CERT" "WERF_SIGN_INTERMEDIATES" "WERF_SIGN_KEY")
+        fi
+        if [[ "${WERF_SIGN_ELF_FILES}" == "1" || "${WERF_BSIGN_ELF_FILES}" == "1" ]]; then
+          REQUIRED_SIGNING_VARS+=("WERF_ELF_PGP_PRIVATE_KEY_FINGERPRINT" "WERF_ELF_PGP_PRIVATE_KEY_PASSPHRASE")
+        fi
+
+        if [[ -z "${WERF_VAULT_AUTH_ROLE_ID}" && -z "${WERF_VAULT_AUTH_JWT}" ]]; then
+          echo "❌ ERROR: Required secret variable WERF_VAULT_AUTH_ROLE_ID or WERF_VAULT_AUTH_JWT is not set!"
+          echo "Please configure this variable in GitLab CI/CD settings -> Variables. See https://github.com/deckhouse/delivery-kit-sdk/blob/main/pkg/signver/hashivault/README.md for details."
+          exit 1
+        fi
+
+        if [[ -z "${WERF_VAULT_AUTH_JWT}" ]]; then
+          # if no JWT variable, then we need to require both WERF_VAULT_AUTH_ROLE_ID and WERF_VAULT_AUTH_SECRET_ID
+          REQUIRED_SIGNING_VARS+=("WERF_VAULT_AUTH_ROLE_ID" "WERF_VAULT_AUTH_SECRET_ID")
+        else
+          # if JWT variable is set, then we need to require WERF_VAULT_AUTH_ROLE
+          REQUIRED_SIGNING_VARS+=("WERF_VAULT_AUTH_JWT" "WERF_VAULT_AUTH_ROLE")
+        fi
+
+        # Check secret variables
+        for var in "${REQUIRED_SIGNING_VARS[@]}"; do
+          if [[ -z "${!var}" ]]; then
+            echo "❌ ERROR: Required secret variable $var is not set!"
+            echo "Please configure this variable in GitLab CI/CD settings -> Variables"
+            exit 1
+          else
+            echo "✅ Secret variable $var is configured"
+          fi
+        done
+      fi
 
     # Setup dmt
     - |
+      echo "🔧 Installing Deckhouse Module Tool (dmt)..."
       trdl add dmt https://trrr.flant.dev/trdl-dmt/ 3 e77d785600a8c8612b84b93a5a2e4c48188d68f7478356d0708213e928bf67b024ed412e702dc32930da5c5bfc9b1c44be3ee7a292f923327815c91c6c3c3833
       source $(trdl use dmt 0 stable)
 
     - |
       if [[ ! -z "${BASE_IMAGES_VERSION}" ]]; then
-        echo "Downloading base_images.yml ${BASE_IMAGES_VERSION}"
+        echo "🔧 Downloading base_images.yml ${BASE_IMAGES_VERSION}"
         curl --fail -sSLO https://fox.flant.com/api/v4/projects/deckhouse%2Fbase-images/packages/generic/base_images/${BASE_IMAGES_VERSION}/base_images.yml
       else
-        echo "DO NOT download base_images.yml because BASE_IMAGES_VERSION is empty"
+        echo "⚠️ DO NOT download base_images.yml because BASE_IMAGES_VERSION is empty"
       fi
 
     # Download deckhouse lib-helm archive
     - |
       if [[ -n "${DECKHOUSE_LIB_HELM_VERSION}"  ]]; then
+        echo "🔧 Downloading deckhouse lib-helm ${DECKHOUSE_LIB_HELM_VERSION}"
         mkdir charts
         curl --fail -sSLO https://github.com/deckhouse/lib-helm/releases/download/deckhouse_lib_helm-${DECKHOUSE_LIB_HELM_VERSION}/deckhouse_lib_helm-${DECKHOUSE_LIB_HELM_VERSION}.tgz --output-dir ./charts
       fi
@@ -133,6 +235,7 @@ stages:
     # Add ssh keys
     - |
       if [[ -n "${SOURCE_REPO_SSH_KEY}" || -n "${SVACE_ANALYZE_SSH_PRIVATE_KEY_B64}" ]]; then
+        echo "🔧 Adding ssh keys for svace analyze..."
 
         eval $(ssh-agent)
         trap "kill -3 ${SSH_AGENT_PID}" ERR EXIT HUP INT QUIT TERM
