* add sign images code from `feat/signing_images` branch
Signed-off-by: Ivan.Makeev <ivan.makeev@flant.com>

diff --git a/templates/multi-repo/Setup.gitlab-ci.yml b/templates/multi-repo/Setup.gitlab-ci.yml
--- a/templates/multi-repo/Setup.gitlab-ci.yml
+++ b/templates/multi-repo/Setup.gitlab-ci.yml
@@ -14,6 +14,26 @@
 #   SVACE_ANALYZE_SSH_USER: - ssh user to connect with to svace analyze vm
 #   SVACE_ANALYZE_SSH_PRIVATE_KEY_B64 - svace analyze server ssh private key
 
+#   Variables for sign (must be configured in GitLab CI/CD Variables):
+#   WERF_ELF_PGP_PRIVATE_KEY_FINGERPRINT - GPG key fingerprint
+#   WERF_ELF_PGP_PRIVATE_KEY_PASSPHRASE - GPG key passphrase
+#   VAULT_ADDR - URL to Vault address
+#   WERF_SIGN_CERT - certificate for signing images
+#   WERF_SIGN_INTERMEDIATES - intermediate certificates
+#   VAULT_ROLE_ID - ID role for access to Vault
+#   VAULT_SECRET_ID - secret ID for access to Vault
+#   WERF_SIGN_KEY - private key for signing
+#
+#   Variables configured in ci file:
+#   WERF_BSIGN_ELF_FILES=1 - enable binary signing
+#   WERF_SIGN_MANIFEST: "true" - enable image signing
+#   WERF_ANNOTATE_LAYERS_WITH_DM_VERITY_ROOT_HASH = true - add dm-verity hashes to layers
+#   WERF_SIGN_ELF_FILES: "1" - enable elf signing
+#
+#   PACKAGE_TOKEN - token for access to internal repository for downloading werf binary
+#
+#   The GPG key is located locally on the Gitlab runner
+#   Werf must be installed manually
 
 variables:
   ##############################
@@ -55,6 +75,12 @@ variables:
     value: ${CI_REGISTRY_IMAGE}/${MODULES_MODULE_NAME}
   WERF_VERSION: "2 stable"
 
+  WERF_SIGN_VERSION: "v2.47.7-dk-dev"
+  WERF_SIGN_MANIFEST: "1"
+  WERF_SIGN_ELF_FILES: "1"
+  WERF_BSIGN_ELF_FILES: "1"
+  WERF_ANNOTATE_LAYERS_WITH_DM_VERITY_ROOT_HASH: "1"
+
 stages:
   - lint
   - cleanup
@@ -85,16 +111,38 @@ stages:
   before_script:
     # Setup trdl
     - |
-      trdl_version=$(curl -s https://tuf.trdl.dev/targets/channels/0/stable)
-      curl -sSLO "https://tuf.trdl.dev/targets/releases/$trdl_version/linux-amd64/bin/trdl"
-      install -D trdl ~/bin/trdl
-      rm trdl
-      export PATH=$PATH:~/bin
+      TRDL_ROOT="${HOME}/.trdl"
+      trdl_target_version=$(curl -s https://tuf.trdl.dev/targets/channels/0/stable)
+      TRDL_BIN="${TRDL_ROOT}/releases/${trdl_target_version}/trdl"
+      if [[ ! -x "${TRDL_BIN}" ]]; then
+        mkdir -p "${TRDL_ROOT}/releases/${trdl_target_version}"
+        curl -sSLO "https://tuf.trdl.dev/targets/releases/${trdl_target_version}/linux-amd64/bin/trdl"
+        mv trdl "${TRDL_BIN}"
+        chmod +x "${TRDL_BIN}"
+      fi
+      ln -sfn "releases/${trdl_target_version}" "${TRDL_ROOT}/current"
+      export PATH="${TRDL_ROOT}/current:${PATH}"
 
     # Setup werf
     - |
-      trdl add werf https://tuf.werf.io 1 b7ff6bcbe598e072a86d595a3621924c8612c7e6dc6a82e919abe89707d7e3f468e616b5635630680dd1e98fc362ae5051728406700e6274c5ed1ad92bea52a2
-      source $(trdl use werf ${WERF_VERSION:-1.2 stable})
+      if [[ -n "${WERF_SIGN_VERSION}" ]]; then
+        echo "🔧 Downloading werf $WERF_SIGN_VERSION binary with signing support from internal repository..."
+
+        curl --fail -sSL -o ~/bin/werf \
+        -H "PRIVATE-TOKEN: $PACKAGE_TOKEN" \
+        "https://fox.flant.com/api/v4/projects/4052/packages/generic/werf/${WERF_SIGN_VERSION}/werf"
+        type -a werf
+        chmod +x ~/bin/werf
+        export PATH=~/bin:$PATH
+      else
+        echo "Installing werf $WERF_VERSION via trdl..."
+        trdl add werf https://tuf.werf.io 1 b7ff6bcbe598e072a86d595a3621924c8612c7e6dc6a82e919abe89707d7e3f468e616b5635630680dd1e98fc362ae5051728406700e6274c5ed1ad92bea52a2
+        source $(trdl use werf ${WERF_VERSION:-1.2 stable})
+      fi
+
+      # Check werf version
+      werf version
+
       source $(werf ci-env gitlab --as-file)
 
       # Login to gitlab registry by default
@@ -109,6 +157,34 @@ stages:
       fi
       echo "Logging in to registry ${MODULES_REGISTRY}..."
       werf cr login -u ${MODULES_REGISTRY_LOGIN} -p ${MODULES_REGISTRY_PASSWORD} ${MODULES_REGISTRY}
+
+    - |
+      if [[ -n "${WERF_SIGN_VERSION}" ]]; then
+        echo "🔐 Checking required signing variables..."
+
+        # Variables that must be set in secrets CI/CD
+        REQUIRED_SIGNING_VARS=(
+          "WERF_SIGN_CERT"
+          "WERF_SIGN_INTERMEDIATES"
+          "WERF_SIGN_KEY"
+          "VAULT_ADDR"
+          "VAULT_ROLE_ID"
+          "VAULT_SECRET_ID"
+          "WERF_ELF_PGP_PRIVATE_KEY_FINGERPRINT"
+          "WERF_ELF_PGP_PRIVATE_KEY_PASSPHRASE"
+        )
+
+        # Check secret variables
+        for var in "${REQUIRED_SIGNING_VARS[@]}"; do
+          if [[ -z "${!var}" ]]; then
+            echo "❌ ERROR: Required secret variable $var is not set!"
+            echo "Please configure this variable in GitLab CI/CD settings -> Variables"
+            exit 1
+          else
+            echo "✅ Secret variable $var is configured"
+          fi
+        done
+      fi
 
     # Setup dmt
     - |
