test
Signed-off-by: Maksim Khimchenko <maksim.khimchenko@flant.com>

diff --git a/templates/Build.gitlab-ci.yml b/templates/Build.gitlab-ci.yml
--- a/templates/Build.gitlab-ci.yml
+++ b/templates/Build.gitlab-ci.yml
@@ -1,24 +1,43 @@
-# variables:
-#   $MODULES_MODULE_SOURCE - base URL for the registry, e.g., registry.example.com/deckhouse/modules
-#   $MODULES_MODULE_NAME (Optional) - module name, by default it is equal to the project name
-#   $WERF_REPO - registry path, default ${MODULES_MODULE_SOURCE}/${MODULES_MODULE_NAME}
-
-variables:
-  SVACE_ENABLED:
+inputs:
+  module_source:
+    description: 'Registry repository address for of the module, e.g., registry.example.com/module-source'
+    type: string
+  module_name:
+    description: 'Name of the module, e.g., my-module'
+    type: string
+  module_tag:
+    description: 'The version of the module to deploy to release channel, e.g., v1.21.1'
+    type: string
+  secondary_repo:
+    description: 'Secondary repository address for module, e.g., registry.example.com/module-source/module_name'
+    type: string
+    default: ""
+  source_repo:
+    description: "Source repository address for the module"
+    type: string
+    default: ""
+  source_repo_ssh_key:
+    description: "SSH private key for the source repository"
+    type: string
+    default: ""
+  svace_analyze_host:
+    description: 'fqdn address to the svace analyze vm'
+    type: string
+    default: ""
+  svace_analyze_ssh_user:
+    description: 'ssh user to connect with to svace analyze vm'
+    type: string
+    default: ""
+  svace_analyze_ssh_key:
+    description: "SSH private key for the svace analyze server"
+    type: string
+    default: ""
+  svace_enabled:
     description: "Enable Svace analysis"
     value: "false"
     options:
       - "true"
       - "false"
-#   SVACE_ANALYZE_HOST:
-#     description: "hostname of the svace analyze vm"
-#     value: "${SVACE_ANALYZE_HOST}"
-#   SVACE_ANALYZE_SSH_USER:
-#     description: "ssh user to connect with to svace analyze vm"
-#     value: "${SVACE_ANALYZE_SSH_USER}"
-#   SVACE_ANALYZE_SSH_PRIVATE_KEY:
-#     description: "svace analyze server ssh private key"
-#     value: "${SVACE_ANALYZE_SSH_PRIVATE_KEY}"
 
 .lint:
   stage: build
@@ -30,8 +49,62 @@ variables:
     - if: $CI_COMMIT_TAG
   allow_failure: true
 
-.build:
+build:
   stage: build
+  variables:
+    MODULE_SOURCE: $[[ inputs.module_source ]]
+    MODULE_NAME: $[[ inputs.module_name ]]
+    MODULE_TAG: $[[ inputs.module_tag ]]
+    SECONDARY_REPO: $[[ inputs.secondary_repo ]]
+    SOURCE_REPO: $[[ inputs.source_repo ]]
+    SOURCE_REPO_SSH_KEY: $[[ inputs.source_repo_ssh_key ]]
+    SVACE_ANALYZE_HOST: $[[ inputs.svace_analyze_host ]]
+    SVACE_ANALYZE_SSH_USER: $[[ inputs.svace_analyze_ssh_user ]]
+    SVACE_ANALYZE_SSH_KEY: $[[ inputs.svace_analyze_ssh_key ]]
+    SVACE_ENABLED: $[[ inputs.svace_enabled ]]
+  before_script:
+    - |
+      if [[ "${SOURCE_REPO_SSH_KEY}"  != '' || "${SOURCE_REPO_SSH_KEY}" != '' ]]
+      if [[ -n "${SSH_AUTH_SOCK}" && -n "${SSH_AGENT_PID}" ]]; then
+          echo "Existed ssh agent pid: ${SSH_AGENT_PID}"
+          echo "Existed ssh auth sock: ${SSH_AUTH_SOCK}"
+          echo "INIT_SSH_AGENT_PID=${SSH_AGENT_PID}" >> $GITHUB_OUTPUT
+          echo "INIT_SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_OUTPUT
+          eval "$(ssh-agent -s)" > /dev/null
+      else
+          eval "$(ssh-agent -s)" > /dev/null
+      fi
+      mkdir -p ~/.ssh
+      touch ~/.ssh/known_hosts
+      echo "New ssh agent pid: ${SSH_AGENT_PID}"
+      echo "New ssh auth sock: ${SSH_AUTH_SOCK}"
+      echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> $GITHUB_ENV
+      echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV
+
+    # Add to known_hosts
+    - |
+      [[ -z "${SOURCE_REPO}" ]] && exit 0
+      HOST=$(grep -oP '(?<=@)[^/:]+' <<< ${SOURCE_REPO})
+      HOST_KEYS=$(ssh-keyscan -H "$HOST" 2>/dev/null)
+      while IFS= read -r KEY_LINE; do
+        CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
+        if ! grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
+          echo "$KEY_LINE" >> ~/.ssh/known_hosts
+        fi
+      done <<< "$HOST_KEYS"
+
+      [[ -z "${SVACE_ANALYZE_HOST}" ]] && exit 0
+      echo "Adding svace ssh key (ignoring errors)."
+      set +e
+      HOST=${SVACE_ANALYZE_HOST}
+      HOST_KEYS=$(ssh-keyscan -H "$HOST" 2>/dev/null)
+      while IFS= read -r KEY_LINE; do
+        CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
+        if ! grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
+          echo "$KEY_LINE" >> ~/.ssh/known_hosts
+        fi
+      done <<< "$HOST_KEYS"
+      set -e
   script:
     # Build images
     - |
