build with WERF_REPO
Signed-off-by: Maksim Khimchenko <maksim.khimchenko@flant.com>

diff --git a/templates/Setup.gitlab-ci.yml b/templates/Setup.gitlab-ci.yml
--- a/templates/Setup.gitlab-ci.yml
+++ b/templates/Setup.gitlab-ci.yml
@@ -1,3 +1,20 @@
+# variables:
+#   $MODULES_MODULE_SOURCE - base URL for the registry, e.g., registry.example.com/deckhouse/modules
+#   $MODULES_MODULE_NAME (Optional) - module name, by default it is equal to the project name
+#   $WERF_REPO - registry path, default ${MODULES_MODULE_SOURCE}/${MODULES_MODULE_NAME}
+#   $DEV_MODULES_REGISTRY - dev registry path
+#   $DEV_MODULES_REGISTRY_LOGIN - login to dev registry
+#   $DEV_MODULES_REGISTRY_PASSWORD - password to dev registry
+#   $SOURCE_REPO - Source repository address for the module
+#   $SOURCE_REPO_SSH_KEY - SSH private key for the source repository
+#   $DEV_MODULES_REGISTRY_PASSWORD - password to dev registry
+#   $DEV_MODULES_REGISTRY_PASSWORD - password to dev registry
+#   $DEV_MODULES_REGISTRY_PASSWORD - password to dev registry
+#   $DEV_MODULES_REGISTRY_PASSWORD - password to dev registry
+#   SVACE_ANALYZE_HOST - hostname of the svace analyze vm
+#   SVACE_ANALYZE_SSH_USER: - ssh user to connect with to svace analyze vm
+#   SVACE_ANALYZE_SSH_PRIVATE_KEY- svace analyze server ssh private key
+
 variables:
   MODULES_MODULE_NAME: "${CI_PROJECT_NAME}"
   MODULES_MODULE_TAG: ${CI_COMMIT_REF_NAME}
@@ -47,35 +64,41 @@ before_script:
 
     eval $(ssh-agent)
     trap "kill -3 ${SSH_AGENT_PID}" ERR EXIT HUP INT QUIT TERM
-    [[ -n "${SOURCE_REPO_SSH_KEY}" ]] && ssh-add - <<< "${SOURCE_REPO_SSH_KEY}"
-    [[ -n "${SVACE_ANALYZE_SSH_PRIVATE_KEY}" ]] && ssh-add - <<< "${SVACE_ANALYZE_SSH_PRIVATE_KEY}"
-
     export SSH_KNOWN_HOSTS=~/.ssh/known_hosts
     mkdir -p ~/.ssh
     touch ~/.ssh/known_hosts
 
-    [[ -z "${SOURCE_REPO}" ]] && exit 0
-    HOST=$(grep -oP '(?<=@)[^/:]+' <<< ${SOURCE_REPO})
-    HOST_KEYS=$(ssh-keyscan -H "$HOST" 2>/dev/null)
-    while IFS= read -r KEY_LINE; do
-      CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
-      if ! grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
-        echo "$KEY_LINE" >> ~/.ssh/known_hosts
+    if [[ -n "${SOURCE_REPO_SSH_KEY}" ]]; then
+      ssh-add - <<< "${SOURCE_REPO_SSH_KEY}"
+      if [[ -n "${SOURCE_REPO}" ]]; then
+        HOST=$(grep -oP '(?<=@)[^/:]+' <<< ${SOURCE_REPO})
+        HOST_KEYS=$(ssh-keyscan -H "$HOST" 2>/dev/null)
+        while IFS= read -r KEY_LINE; do
+          CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
+          if ! grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
+            echo "$KEY_LINE" >> ~/.ssh/known_hosts
+          fi
+        done <<< "$HOST_KEYS"
       fi
-    done <<< "$HOST_KEYS"
+    fi
 
-    [[ -z "${SVACE_ANALYZE_HOST}" ]] && exit 0
-    echo "Adding svace ssh key (ignoring errors)."
-    set +e
-    HOST=${SVACE_ANALYZE_HOST}
-    HOST_KEYS=$(ssh-keyscan -H "$HOST" 2>/dev/null)
-    while IFS= read -r KEY_LINE; do
-      CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
-      if ! grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
-        echo "$KEY_LINE" >> ~/.ssh/known_hosts
+    if [[ -n "${SVACE_ANALYZE_SSH_PRIVATE_KEY}" ]]; then
+      ssh-add - <<< "${SVACE_ANALYZE_SSH_PRIVATE_KEY}"
+      if [[ -n "${SVACE_ANALYZE_HOST}" ]]; then
+        echo "Adding svace ssh key (ignoring errors)."
+        set +e
+        HOST=${SVACE_ANALYZE_HOST}
+        HOST_KEYS=$(ssh-keyscan -H "$HOST" 2>/dev/null)
+        while IFS= read -r KEY_LINE; do
+          CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
+          if ! grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
+            echo "$KEY_LINE" >> ~/.ssh/known_hosts
+          fi
+        done <<< "$HOST_KEYS"
+        set -e
       fi
-    done <<< "$HOST_KEYS"
-    set -e
+    fi
+
 stages:
   - build
   - deploy
